.TH ACOSH 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
acosh \- inverzní hyperbolický cosinus
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BR "double acosh(double " x );
.fi
.SH POPIS
Funkce \fBacosh()\fP počítá hodnotu inverzního hyperbolického cosinu čísla 
\fIx\fP; což je hodnota, jejíž hyperbolický cosinus je \fIx\fP.
Je-li \fIx\fP menší než 1.0, \fBacosh()\fP vrací \fInot-a-number\fP (NaN)
a nastaví proměnnou \fIerrno\fP .
.SH CHYBY
.TP
.B EDOM
\fIx\fP není z definičního oboru.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR asinh "(3), " atanh "(3), " cosh "(3), " sinh "(3), " tanh (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
