.TH ACOS 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
acos \- funkce arccos
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BI "double acos(double " x );
.fi
.SH POPIS
Funkce \fBacos()\fP počítá arccos čísla \fIx\fP; což je hodnota, jejíž
cosinus je \fIx\fP.  Je-li \fIx\fP mimo interval
od \-1 do 1, funkce \fBacos()\fP selže a je nastavena proměnná \fIerrno\fP.
.SH NÁVRATOVÁ HODNOTA
Funkce \fBacos()\fP vrací arccos v radiánech. Její návratová hodnota může
být od 0 do PI včetně.
.SH CHYBY
.TP
.B EDOM
\fIx\fP není z definičního oboru.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR asin "(3), " atan "(3), " atan2 "(3), " cos "(3), " sin "(3), " tan (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
