.TH ASINH 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
asinh \- inverzní hyperbolický sinus
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BI "double asinh(double " x );
.fi
.SH POPIS
Funkce \fBasinh()\fP počítá inverzní hyperbolický sinus čísla \fIx\fP; což
je hodnota, jejíž hyperbolický sinus je \fIx\fP.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR acosh "(3), " atanh "(3), " cosh "(3), " sinh "(3), " tanh (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
