.TH ATOI 3  "6.ledna 1997" "GNU" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
atoi \- převádí řetězec na číslo typu integer
.SH SYNTAXE
.nf
.B #include <stdlib.h>
.sp
.BI "int atoi(const char *" nptr );
.fi
.SH POPIS
Funkce \fBatoi()\fP převádí úvodní část řetězce 
\fInptr\fP na číslo typu integer. Její chování je totožné s funkcí
.sp
.RS
.B strtol(nptr, (char **)NULL, 10);
.RE
.sp
kromě toho, že \fBatoi()\fP nedetekuje chyby.
.SH NÁVRATOVÁ HODNOTA
Převedená hodnota.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR atof "(3), " atol "(3), " strtod "(3), " strtol "(3), " strtoul (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
