.TH CEIL 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
ceil \- nejmenší celé číslo ne menší než x
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BI "double ceil (double " x );
.fi
.SH POPIS
Funkce \fBceil()\fP zaokrouhlí číslo \fIx\fP nahoru na nejbližší celé číslo.
a toto číslo vrátí jako double.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR abs "(3), " fabs "(3), " floor "(3), " labs "(3), " rint (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
