.TH COS 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
cos \- funkce cosinus
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BI "double cos(double " x );
.fi
.SH POPIS
Funkce \fBcos()\fP vrací cosinus čísla \fIx\fP, kde \fIx\fP je hodnota v
radiánech.
.SH NÁVRATOVÁ HODNOTA
Oborem hodnot funkce \fBcos()\fP je uzavřený interval od \-1 do 1.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR acos "(3), " asin "(3), " atan "(3), " atan2 "(3), " sin "(3), " tan (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
