.TH COSH 3  "5.ledna 1997" "" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
cosh \- funkce hyperbolický cosinus
.SH SYNTAXE
.nf
.B #include <math.h>
.sp
.BI "double cosh(double " x );
.fi
.SH POPIS
Funkce \fBcosh()\fP vrací hodnotu hyperbolického cosinu čísla \fIx\fP, který
je definován jako (exp(x) + exp(-x)) / 2.
.SH SPLŇUJE STANDARDY
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH DALŠÍ INFORMACE
.BR acosh "(3), " asinh "(3), " atanh "(3), " sinh "(3), " tanh (3)
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
