.TH UNDOCUMENTED 2 "5.ledna 1997" "Linux 1.3.86" "Linux - příručka programátora"
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
nedokumentovaná systémová volání
.SH SYNTAXE
Nedokumentovaná systémová volání.
.SH POPIS
Nyní je v jádře 1.3.88 163 volání, která jsou obsažena v 
.IR /usr/include/asm/unistd.h .
Tato stránka obsahuje ta z nich, která jsou již implementována, ale ještě
nejsou popsána v manuálových stránkách.
Některá z těchto volání ještě nemají prototyp v hlavičkových souborech
knihovny libc.
.SH ŽÁDOST
Máte-li o těchto voláních nějaké informace, prosím podívejte se do
zdrojových textů jádra a napište manuálovou stránku (podobného stylu jako
ostatní stránky v sekci 2) a pošlete ji na adresu
.B aeb@cwi.nl ,
abychom ji mohli dát do další distribuce manuálových stránek.
.SH SITUACE
Není žádné nedokumentované volání jádra.
.SH DALŠÍ INFORMACE
.BR obsolete "(2), " unimplemented "(2)"
.SH VAROVÁNÍ
Překlad je pravděpodobně zastaralý. Pokud chcete pomoci s jeho aktualizací, zamiřte na http://man-pages-cs-wiki.homelinux.net/
